### ISSUE TITLE
To rename your-rents-services to your-rents-web

### ISSUE THREAD

**Issue by egch** [your-rents/your-rents-backend#26]
To date the module _your-rents-services_ is exclusively used for having a web interface to the application.
Moreover the service components, currently packaged into  _your-rents-core_ module, cause confusion, regarding the scope of the module, with the _your-rents-services_ module.
According to me makes sense to rename it as _your-rents-web_.

**Comment by benfante** [comment]
No, it's not a web interface, it's a rest api. Maybe we could change the name to _your-rents-api_?

**Comment by egch** [comment]
Yes, your-rents-api would be fine
